### ISSUE TITLE
在kali arm64虚拟机中运行报错

### ISSUE THREAD

**Issue by 0xlo0p** [boy-hack/ksubdomain#44]
_              _         _                       _       
| | _____ _   _| |__   __| | ___  _ __ ___   __ _(_)_ __  
| |/ / __| | | | '_ \ / _' |/ _ \| '_ ' _ \ / _| | | '_ \
|   <\__ \ |_| | |_) | (_| | (_) | | | | | | (_| | | | | |
|_|\_\___/\__,_|_.__/ \__,_|\___/|_| |_| |_|\__,_|_|_| |_|

[INFO] Current Version: 1.9.9
.............................................................panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x78a43c]

goroutine 1 [running]:
github.com/boy-hack/ksubdomain/core/device.AutoGetDevices()
        /home/kali/go/pkg/mod/github.com/boy-hack/ksubdomain@v1.9.9/core/device/device.go:114 +0x32c
github.com/boy-hack/ksubdomain/core/options.GetDeviceConfig()
        /home/kali/go/pkg/mod/github.com/boy-hack/ksubdomain@v1.9.9/core/options/options.go:114 +0xd4
main.init.func2(0x4000038d40)
        /home/kali/go/pkg/mod/github.com/boy-hack/ksubdomain@v1.9.9/cmd/ksubdomain/enum.go:193 +0x944
github.com/urfave/cli/v2.(*Command).Run(0xcdbce0, 0x4000038580)
        /home/kali/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dc
github.com/urfave/cli/v2.(*App).RunContext(0x40001224e0, {0x9f59d8, 0x128b380}, {0x40000201e0, 0x6, 0x6})
        /home/kali/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x844
github.com/urfave/cli/v2.(*App).Run(...)
        /home/kali/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/kali/go/pkg/mod/github.com/boy-hack/ksubdomain@v1.9.9/cmd/ksubdomain/cmd.go:22 +0x128
[total: 0] ksubdomain: []
len [0]
[total: 0] theHarvester: []
len [0]

**Comment by boy-hack** [comment]
新版重试下
