### ISSUE TITLE
Mac 运行报错

### ISSUE THREAD

**Issue by godzeo** [boy-hack/ksubdomain#9]
<img width="329" alt="image" src="https://user-images.githubusercontent.com/64398024/156171971-035b4e94-54d8-4608-b487-9dfc350668cd.png">

```
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/64398024/156172516-3b9b6616-d756-4ff8-8115-4b66cf4bae86.png">

```
╰─➤  ./ksubdomain e -d baidu.com

 _              _         _                       _
| | _____ _   _| |__   __| | ___  _ __ ___   __ _(_)_ __
| |/ / __| | | | '_ \ / _' |/ _ \| '_ ' _ \ / _| | | '_ \
|   <\__ \ |_| | |_) | (_| | (_) | | | | | | (_| | | | | |
|_|\_\___/\__,_|_.__/ \__,_|\___/|_| |_| |_|\__,_|_|_| |_|

[INFO] Current Version: 1.8.3
[INFO] libpcap version 1.9.1
[INFO] 读取配置ksubdomain.yaml成功!
[INFO] Use Device: en0
[INFO] Use IP:192.168.1.2
[INFO] Local Mac: f8:ff:c2:50:42:86
[INFO] GateWay Mac: c8:5a:9f:1d:88:0a
[INFO] DNS:[223.5.5.5 223.6.6.6 180.76.76.76 119.29.29.29 182.254.116.116 114.114.114.115]
[INFO] 检测域名:[baidu.com]
[INFO] Rate:14696pps
[INFO] FreePort:49763
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2052dc9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2052dc9e
stack: frame={sp:0x70000c629e58, fp:0x70000c629ea8} stack=[0x70000c5aa338,0x70000c629f38)
0x000070000c629d58:  0x010070000c629d78  0x0000000000000004
0x000070000c629d68:  0x000000000000001f  0x00007fff2052dc9e
0x000070000c629d78:  0x0b01dfacedebac1e  0x0000000000000001
0x000070000c629d88:  0x00000000040362d1 <runtime.throw+0x0000000000000071>  0x000070000c629e28
0x000070000c629d98:  0x000000000431e23a  0x000070000c629de0
0x000070000c629da8:  0x0000000004036588 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000c0001021a0
0x000070000c629db8:  0x0000000000000001  0x0000000000000001
0x000070000c629dc8:  0x000070000c629e28  0x00000000040362d1 <runtime.throw+0x0000000000000071>
0x000070000c629dd8:  0x000000c0001021a0  0x000070000c629e18
0x000070000c629de8:  0x0000000004036510 <runtime.fatalthrow+0x0000000000000050>  0x000070000c629df8
0x000070000c629df8:  0x0000000004036540 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c0001021a0
0x000070000c629e08:  0x00000000040362d1 <runtime.throw+0x0000000000000071>  0x000070000c629e28
0x000070000c629e18:  0x000070000c629e48  0x00000000040362d1 <runtime.throw+0x0000000000000071>
0x000070000c629e28:  0x000070000c629e30  0x0000000004036300 <runtime.throw.func1+0x0000000000000000>
0x000070000c629e38:  0x000000000432303a  0x000000000000002a
0x000070000c629e48:  0x000070000c629e98  0x000000000404b8d6 <runtime.sigpanic+0x0000000000000396>
0x000070000c629e58: <0x000000000432303a  0x000000000403f19e <runtime.checkTimers+0x000000000000005e>
0x000070000c629e68:  0x00000ac0c6167f6b  0x000070000c629e98
0x000070000c629e78:  0x000070000c629ea0  0x000000000403d78f <runtime.execute+0x000000000000012f>
0x000070000c629e88:  0x000000c0000b16f8  0x0000000200000001
0x000070000c629e98:  0x000070000c629ee0 !0x00007fff2052dc9e
0x000070000c629ea8: >0x000070000c629ee0  0x000000000464c000
0x000070000c629eb8:  0x0000000000000241  0x00000000040e4605 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x000070000c629ec8:  0x000000000406777f <runtime.syscall+0x000000000000001f>  0x000000c000063368
0x000070000c629ed8:  0x000000c0000b16c0  0x000000c000063338
0x000070000c629ee8:  0x0000000004065610 <runtime.asmcgocall+0x0000000000000070>  0x000000000403f4cd <runtime.park_m+0x000000000000014d>
0x000070000c629ef8:  0x000000c0000001a0  0x0000000400000002
0x000070000c629f08:  0x000000c0001021a0  0x000000c0000001a0
0x000070000c629f18:  0x00000000000004f0  0x000000c0000b16c0
0x000070000c629f28:  0x000000c0000001a0  0x000070000c629f50
runtime.throw({0x432303a, 0x403f19e})
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2052dc9e
stack: frame={sp:0x70000c629e58, fp:0x70000c629ea8} stack=[0x70000c5aa338,0x70000c629f38)
0x000070000c629d58:  0x010070000c629d78  0x0000000000000004
0x000070000c629d68:  0x000000000000001f  0x00007fff2052dc9e
0x000070000c629d78:  0x0b01dfacedebac1e  0x0000000000000001
0x000070000c629d88:  0x00000000040362d1 <runtime.throw+0x0000000000000071>  0x000070000c629e28
0x000070000c629d98:  0x000000000431e23a  0x000070000c629de0
0x000070000c629da8:  0x0000000004036588 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000c0001021a0
0x000070000c629db8:  0x0000000000000001  0x0000000000000001
0x000070000c629dc8:  0x000070000c629e28  0x00000000040362d1 <runtime.throw+0x0000000000000071>
0x000070000c629dd8:  0x000000c0001021a0  0x000070000c629e18
0x000070000c629de8:  0x0000000004036510 <runtime.fatalthrow+0x0000000000000050>  0x000070000c629df8
0x000070000c629df8:  0x0000000004036540 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c0001021a0
0x000070000c629e08:  0x00000000040362d1 <runtime.throw+0x0000000000000071>  0x000070000c629e28
0x000070000c629e18:  0x000070000c629e48  0x00000000040362d1 <runtime.throw+0x0000000000000071>
0x000070000c629e28:  0x000070000c629e30  0x0000000004036300 <runtime.throw.func1+0x0000000000000000>
0x000070000c629e38:  0x000000000432303a  0x000000000000002a
0x000070000c629e48:  0x000070000c629e98  0x000000000404b8d6 <runtime.sigpanic+0x0000000000000396>
0x000070000c629e58: <0x000000000432303a  0x000000000403f19e <runtime.checkTimers+0x000000000000005e>
0x000070000c629e68:  0x00000ac0c6167f6b  0x000070000c629e98
0x000070000c629e78:  0x000070000c629ea0  0x000000000403d78f <runtime.execute+0x000000000000012f>
0x000070000c629e88:  0x000000c0000b16f8  0x0000000200000001
0x000070000c629e98:  0x000070000c629ee0 !0x00007fff2052dc9e
0x000070000c629ea8: >0x000070000c629ee0  0x000000000464c000
0x000070000c629eb8:  0x0000000000000241  0x00000000040e4605 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x000070000c629ec8:  0x000000000406777f <runtime.syscall+0x000000000000001f>  0x000000c000063368
0x000070000c629ed8:  0x000000c0000b16c0  0x000000c000063338
0x000070000c629ee8:  0x0000000004065610 <runtime.asmcgocall+0x0000000000000070>  0x000000000403f4cd <runtime.park_m+0x000000000000014d>
0x000070000c629ef8:  0x000000c0000001a0  0x0000000400000002
0x000070000c629f08:  0x000000c0001021a0  0x000000c0000001a0
0x000070000c629f18:  0x00000000000004f0  0x000000c0000b16c0
0x000070000c629f28:  0x000000c0000001a0  0x000070000c629f50
runtime.sigpanic()
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 15 [syscall]:
syscall.syscall(0x40e4600, 0x1, 0x40087468, 0xc0000633f8)
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000063368 sp=0xc000063348 pc=0x406225b
syscall.syscall(0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x26 fp=0xc0000633b0 sp=0xc000063368 pc=0x4067f06
golang.org/x/sys/unix.ioctl(0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20201201145000-ef89a241ccb3/unix/zsyscall_darwin_amd64.go:731 +0x39 fp=0xc0000633e0 sp=0xc0000633b0 pc=0x40e4299
golang.org/x/sys/unix.IoctlGetWinsize(...)
	/Users/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20201201145000-ef89a241ccb3/unix/ioctl.go:66
golang.org/x/crypto/ssh/terminal.GetSize(0x0)
	/Users/runner/go/pkg/mod/golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9/ssh/terminal/util.go:80 +0x2c fp=0xc000063410 sp=0xc0000633e0 pc=0x422f2cc
github.com/boy-hack/ksubdomain/core.GetWindowWith()
	/Users/runner/work/ksubdomain/ksubdomain/core/util.go:57 +0x55 fp=0xc000063430 sp=0xc000063410 pc=0x4230675
github.com/boy-hack/ksubdomain/runner.(*runner).handleResult(0xc0000a56c0, {0x0, 0x0})
	/Users/runner/work/ksubdomain/ksubdomain/runner/result.go:20 +0x45 fp=0xc0000637b8 sp=0xc000063430 pc=0x426f045
github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration·dwrap·6()
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:224 +0x2e fp=0xc0000637e0 sp=0xc0000637b8 pc=0x4271c8e
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x4065901
created by github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:224 +0x1c5

goroutine 1 [select]:
github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration(0xc0000a56c0)
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:230 +0x266
main.glob..func1(0xc000020cc0)
	/Users/runner/work/ksubdomain/ksubdomain/cmd/ksubdomain/enum.go:107 +0x76e
github.com/urfave/cli/v2.(*Command).Run(0x46689c0, 0xc0000205c0)
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc0000b0b60, {0x444f250, 0xc00002a0d0}, {0xc000020080, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/Users/runner/work/ksubdomain/ksubdomain/cmd/ksubdomain/cmd.go:22 +0x126

goroutine 10 [runnable]:
github.com/boy-hack/ksubdomain/runner.New.func1()
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:113
created by github.com/boy-hack/ksubdomain/runner.New
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:113 +0x565

goroutine 11 [runnable]:
github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration·dwrap·4()
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:220
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1
created by github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:220 +0xd1

goroutine 12 [chan receive]:
github.com/boy-hack/ksubdomain/runner.(*runner).sendCycle(0xc0000a56c0, {0x0, 0x0})
	/Users/runner/work/ksubdomain/ksubdomain/runner/send.go:17 +0xaa
created by github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:222 +0xdf

goroutine 13 [runnable]:
github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration·dwrap·5()
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:222
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1
created by github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:222 +0xdf

goroutine 14 [runnable]:
github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration·dwrap·5()
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:222
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1
created by github.com/boy-hack/ksubdomain/runner.(*runner).RunEnumeration
	/Users/runner/work/ksubdomain/ksubdomain/runner/runner.go:222 +0xdf
```

**Comment by 1979139113** [comment]
我也遇到了，不过删除ksubdomain.yaml就可以了

**Comment by boy-hack** [comment]
新版应该修复了，测试下？

**Comment by godzeo** [comment]
> 新版应该修复了，测试下？

好了，没问题了
